#!/usr/bin/env python3
"""Pick final image per scene, verify it loads, emit assets/images.css + images.js + credits."""
import json, urllib.request, re, sys

UA = "PatagoniaTripSite/1.0 (personal travel page)"
data = json.load(open("scripts/images.json"))

# scene -> index into candidate list (default 0); region/aspect-aware overrides
CHOICE = {"condor": 2, "buenos_aires": 1}
SKIP = {"lenga_forest"}          # weak (beetle close-up) — don't use
HERO = "hero_fitzroy"

def head(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA}, method="HEAD")
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.status, r.headers.get("Content-Type"), r.headers.get("Content-Length")

final = {}
credits = []
# Trust the API-provided thumburls (authoritative); apply CHOICE/SKIP.
for scene, picks in data.items():
    if scene in SKIP or not picks:
        continue
    idx = min(CHOICE.get(scene, 0), len(picks) - 1)
    p = picks[idx]
    final[scene] = p["thumb"]
    credits.append({"scene": scene, "title": re.sub(r'^File:', '', p["title"]),
                    "artist": p.get("artist") or "Unknown", "license": p.get("license") or "",
                    "url": p.get("desc_url") or ""})
    print(f"  {scene:16s} <- {p['title'][:50]}")

# Wikimedia rejects arbitrary widths (HTTP 400) — reuse the verified API width.
hero_url = final.get(HERO, "")
hero_hi = hero_url
print(f"\nhero: {hero_hi}")

# emit images.css : background-image utility classes
css = ["/* auto-generated by scripts/generate_assets.py — do not edit by hand */"]
for scene, url in final.items():
    css.append(f".bg-{scene.replace('_','-')}{{background-image:url('{url}');}}")
css.append(f".bg-hero-hi{{background-image:url('{hero_hi}');}}")
open("assets/images.css", "w").write("\n".join(css) + "\n")

# emit images.js : JS map + credits
js = ["/* auto-generated by scripts/generate_assets.py */"]
js.append("window.IMG = " + json.dumps({**final, "hero_hi": hero_hi}, ensure_ascii=False) + ";")
js.append("window.IMG_CREDITS = " + json.dumps(credits, ensure_ascii=False) + ";")
open("assets/images.js", "w").write("\n".join(js) + "\n")

print(f"\nwrote assets/images.css ({len(final)} scenes) + assets/images.js + {len(credits)} credits")
print("scenes:", ", ".join(final.keys()))
fails = [s for s in data if s not in final and s not in SKIP]
if fails:
    print("STILL MISSING:", fails)
